import esbuild from "esbuild";
import process from "process";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import builtins from "builtin-modules";
import { execSync } from "child_process";
import chokidar from "chokidar";
import path from "path";
import fs, { mkdirSync } from "fs";
import crypto from "crypto";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const runBuildMetadataCommand = (command) => execSync(command, {
	encoding: "utf8",
	stdio: ["ignore", "pipe", "pipe"],
});

const getGitTag = () => {
	try {
		return runBuildMetadataCommand("git describe --tags --always").trim();
	} catch (e) {
		return "dev";
	}
};
const gitTag = getGitTag();

const develop = process.argv[2] === "develop";
const staging = process.argv[2] === "staging";
const watch = process.argv[2] === "watch" || process.argv.includes("--watch");
const debug = process.argv[2] === "debug" || watch || staging || develop;
const positionalArgs = process.argv.slice(3).filter((a) => !a.startsWith("--"));
const out = positionalArgs[0] || ".";
const tld = staging ? "dev" : "md";

// Endpoints are overridable at build time so the fork can point at our own
// self-hosted server instead of Relay's proprietary cloud. Defaults preserve
// upstream behaviour when no override is set.
const apiUrl =
	process.env.OBSIDIAN_COLLAB_API_URL || `https://api.system3.${tld}`;
const authUrl =
	process.env.OBSIDIAN_COLLAB_AUTH_URL || `https://auth.system3.${tld}`;
const healthUrl = `${apiUrl}/health?version=${gitTag}`;

// Local-auth mode: skip PocketBase/OAuth and use a fixed stub identity so a
// note can go live against our server without the proprietary login flow.
// Off by default; enable with OBSIDIAN_COLLAB_LOCAL_AUTH=true.
const localAuth = process.env.OBSIDIAN_COLLAB_LOCAL_AUTH === "true";
const localAuthEmail =
	process.env.OBSIDIAN_COLLAB_LOCAL_AUTH_EMAIL || "local@localhost";
const localAuthName = process.env.OBSIDIAN_COLLAB_LOCAL_AUTH_NAME || "Local User";
// Fixed "relay" id used to mark folders as live in local-auth mode (no
// RelayManager/discovery). Must be a valid UUID and identical across the vaults
// that should collaborate. Overridable so separate test groups can diverge.
const localRelayId =
	process.env.OBSIDIAN_COLLAB_LOCAL_RELAY_ID ||
	"00000000-0000-4000-8000-000000000001";
console.log("git tag:", gitTag);
console.log("health URL", healthUrl);
console.log("API_URL", apiUrl);
console.log("AUTH_URL", authUrl);
console.log("LOCAL_AUTH", localAuth, localAuth ? `(${localAuthName} <${localAuthEmail}>)` : "");
if (localAuth) console.log("LOCAL_RELAY_ID", localRelayId);

// Fingerprint the working tree: HEAD commit + hash of uncommitted changes.
// Recompute this to check if a build artifact is stale.
const getSourceFingerprint = () => {
	try {
		const head = runBuildMetadataCommand("git rev-parse --short HEAD").trim();
		const diff = runBuildMetadataCommand("git diff HEAD");
		if (!diff) return head;
		const diffHash = crypto.createHash("sha1").update(diff).digest("hex").slice(0, 8);
		return `${head}+${diffHash}`;
	} catch (e) {
		return "unknown";
	}
};

const writeBuildStatus = (build, result) => {
	const outdir = build.initialOptions.outfile;
	// Derive vault name from outdir (e.g. "vaults/live1/.obsidian/..." → "live1")
	const match = outdir.match(/vaults\/([^/]+)\//);
	const name = match ? match[1] : path.basename(path.dirname(outdir));
	const statusDir = ".build-status";
	fs.mkdirSync(statusDir, { recursive: true });
	const timestamp = new Date().toLocaleTimeString("en-GB", { hour12: false });
	const fingerprint = getSourceFingerprint();
	if (result.errors.length > 0) {
		const errors = result.errors.map(e => e.text).join("\n");
		fs.writeFileSync(`${statusDir}/${name}.log`, `FAIL ${timestamp} src:${fingerprint}\n${errors}\n`);
	} else {
		const stat = fs.statSync(outdir);
		const kb = Math.round(stat.size / 1024);
		fs.writeFileSync(`${statusDir}/${name}.log`, `OK ${timestamp} main.js ${kb}kb src:${fingerprint} → ${outdir}\n`);
	}
};

const NotifyPlugin = {
	name: "on-end",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) {
				execSync(`notify-send "Build Failed"`);
				if (staging) {
					writeBuildStatus(build, result);
				}
			} else if (watch) {
				const tag = getGitTag();
				const outfile = build.initialOptions.outfile;
				const content = fs.readFileSync(outfile, "utf8");
				fs.writeFileSync(outfile, content.replace(/__GIT_TAG__/g, tag));
				console.log(`GIT_TAG: ${tag}`);
				if (staging) {
					writeBuildStatus(build, result);
				}
			}
		});
	},
};

const YjsInternalsPlugin = {
	name: "yjs-internals",
	setup(build) {
		// Keep public Yjs imports and internal helper imports on the same
		// module graph so Item/GC instanceof checks agree in the bundle.
		build.onResolve({ filter: /^yjs$/ }, args => {
			return {
				path: path.resolve("node_modules/yjs/src/index.js"),
			};
		});
		build.onResolve({ filter: /^yjs\/dist\/src\/internals$/ }, args => {
			return {
				path: path.resolve("node_modules/yjs/src/internals.js"),
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
        "moment",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
		YjsInternalsPlugin,
		NotifyPlugin,
	],
	target: "es2018",
	minify: !debug,
	logLevel: "info",
	sourcemap: debug ? "inline" : false,
	define: {
		BUILD_TYPE: debug ? '"debug"' : '"prod"',
		GIT_TAG: watch ? '"__GIT_TAG__"' : `"${gitTag}"`,
		HEALTH_URL: `"${healthUrl}"`,
		API_URL: `"${apiUrl}"`,
		AUTH_URL: `"${authUrl}"`,
		LOCAL_AUTH: `${localAuth}`,
		LOCAL_AUTH_EMAIL: `"${localAuthEmail}"`,
		LOCAL_AUTH_NAME: `"${localAuthName}"`,
		LOCAL_RELAY_ID: `"${localRelayId}"`,
		REPOSITORY: `"No-Instructions/Relay"`,
	},
	treeShaking: true,
	outfile: out + "/main.js",
});

const copyFile = (src, dest) => {
	if (src === dest) {
		return;
	}
	fs.copyFileSync(src, dest);
	console.log(`Copied ${src} to ${dest}`);
};

const watchAndMove = (fnames, mapping) => {
	// only usable on top level directory
	const watcher = chokidar.watch(fnames, {
		ignored: /(^|[\/\\])\./, // ignore dotfiles
		persistent: true,
	});

	watcher.on("change", (filePath) => {
		const destName = mapping[filePath] || filePath;
		const destPath = path.join(out, path.basename(destName));
		copyFile(filePath, destPath);
	});
};

const mapping = {};
const manifest = "manifest.json";
const files = ["styles.css", manifest];

const updateManifest = (manifest) => {
	const manifestPath = path.join(out, path.basename("manifest.json"));
	const raw_manifest = fs.readFileSync(manifestPath);
	const parsed = JSON.parse(raw_manifest);
	parsed.version = gitTag;
	const new_manifest = JSON.stringify(parsed, null, 2);
	console.log(`Set ${manifest} version to ${gitTag}`);
	fs.writeFileSync(manifestPath, new_manifest);
};

const move = (fnames, mapping) => {
	// only usable on top level directory
	mkdirSync(out, { recursive: true });
	for (const fname of fnames) {
		const destName = mapping[fname] || fname;
		const destPath = path.join(out, path.basename(destName));
		copyFile(fname, destPath);
	}
};

if (watch) {
	await context.watch();
	move(files, mapping);
	if (!develop) {
		updateManifest();
	}
	watchAndMove(files, mapping);
} else {
	await context.rebuild();
	move(files, mapping);
	if (!develop && out !== ".") {
		updateManifest();
	}
	process.exit(0);
}
